### ISSUE TITLE
Feature request: Turn off Previous, turn off x of y.

### ISSUE THREAD

**Issue by mlolm** [jaguart/kompl#2]
Would it be possible to easily add the option to not display the previous button.

And also not display x of y?

(so basically show only list title and NEXT button, nothing else)

**Comment by jaguart** [comment]
Fixed in **version 0.4.0**, which is available now.
There are two new options: 
* *description* - set to *false* to remove the `1 of n` descriptive test.
* *backward* - set to *false* to remove the PREV navigation control.
I've also :
* added a new *style* shortcut - **onward** which sets both options to *false* 
* updated the *zam* style to also set these both to false.

Toodlepip.
